// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { env, PrismaConfig } from 'prisma/config';

export default {
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  engine: 'classic',
  datasource: {
    url: env('DATABASE_URL'),
    shadowDatabaseUrl: env('DATABASE_URL'),
    directUrl: env('DATABASE_URL'),
  },
} satisfies PrismaConfig;
