import { gql } from '@apollo/client';
export const UserFragment = gql`
fragment UserFragment on User {
  id
  name
  email
  password
  userName
  emailVerified
  image
  isTwoFactorAuthEnabled
  otpCode
  emailOtpExpiresAt
  incrementalLoginAttempts
  isActive
  createdAt
  updatedAt
  basicInformations {
    id
    firstName
    middleName
    lastName
    suffix
    fullName
    birthDate
    gender
    phoneNumber
    address
    city
    province
    country
    userId
    isActive
    createdAt
    updatedAt
    workInformations {
      id
      employeeNumber
      employeeId
      groupOfCompanyId
      companyId
      departmentId
      positionId
      jobLevelId
      employmentTypeId
      employmentStatusId
      reportingManagerId
      hireDate
      regularizationDate
      firstProbationEvaluationDate
      finalProbationEvaluationDate
      contractEndDate
      seasonalEndDate
      endDate
      workLocationId
      workSetupTypeId
      isActive
      createdAt
      updatedAt
    }
  }
  auditLogs {
    id
    modelId
    modelName
    action
    actionTypeId
    timestamp
    actorId
    oldDetails
    newDetails
    parentId
    isActive
    createdAt
    updatedAt
    inventoryItemId
  }
  actions {
    id
    modelId
    modelName
    action
    actionTypeId
    timestamp
    actorId
    oldDetails
    newDetails
    parentId
    isActive
    createdAt
    updatedAt
    inventoryItemId
  }
  userRoles {
    id
    userId
    roleId
    scopeTypeId
    scopeValues
    conditionOverrides
    assignedById
    expiresAt
    isActive
    createdAt
    updatedAt
  }
  userAssignedBy {
    id
    userId
    roleId
    scopeTypeId
    scopeValues
    conditionOverrides
    assignedById
    expiresAt
    isActive
    createdAt
    updatedAt
  }
  workFlowStepTemplate {
    id
    workflowTemplateId
    stepNumber
    assignmentTypeId
    assignedToUserId
    assignmentRules
    isHaveCondition
    isParallel
    requiredApprovals
    slaHours
    escalationRules
    esignatureRequired
    attachmentRequired
    isActive
    createdAt
    updatedAt
  }
  workFlowInstanceStep {
    id
    instanceId
    stepTemplateId
    stepNumber
    statusId
    assignedToUserId
    startedAt
    actionAt
    comments
    isEditable
    source
    isRequired
    isActive
    createdAt
    updatedAt
  }
  requester {
    id
    title
    description
    requestNumber
    requesterId
    companyId
    departmentId
    dateNeeded
    responsibilityCenterId
    quotationUrl
    quotationAmount
    currency
    workflowTemplateId
    approvedAt
    statusId
    isActive
    createdAt
    updatedAt
  }
  budgetRequester {
    id
    fiscalYear
    statusId
    budgetRefNo
    companyId
    departmentId
    categoryId
    requesterId
    purpose
    specs
    quantity
    remark
    workflowTemplateId
    submittedAt
    approvedAt
    rejectedAt
    requestedAmount
    approvedAmount
    remainingAmount
    currency
    isFrozen
    freezeReason
    frozenAt
    isActive
    createdAt
    updatedAt
  }
}
`;
