import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Geist, Geist_Mono, JetBrains_Mono } from 'next/font/google';
import ApolloProviderWrapper from './_context/GraphQLClient/ApolloProvider/ApolloProviderWrapper';
import './globals.css';
import { Toaster } from 'sonner';
import { TooltipProvider } from '@/components/ui/tooltip';

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html
      lang="en"
      suppressHydrationWarning
      className={cn(geistSans.variable, geistMono.variable, jetbrainsMono.variable, 'antialiased')}
    >
      <body>
        <ApolloProviderWrapper>
          <SessionProvider>
            <TooltipProvider>
            <Toaster
              position="bottom-right"
              toastOptions={{
                style: {
                  '--border-radius': 'calc(var(--radius) + 4px)',
                } as React.CSSProperties,
                classNames: {
                  content: 'flex flex-col gap-2',
                  title: 'font-medium text-sm',
                  description: 'text-xs text-muted-foreground',
                },
              }}
            />
              {children}
            </TooltipProvider>
          </SessionProvider>
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
